version: 2.1

jobs:
  check_tools:
    machine:
      enabled: true
    steps:
      - run:
          name: Check tools
          command: command -v npm

workflows:
  main:
    jobs:
      - check_tools
